### ISSUE TITLE
Request: database migration example

### ISSUE THREAD

**Issue by leifcr** [jaguar-orm/sqflite#6]
If possible, a small example with recommendations on how to add migrations in a flutter application.

**Comment by pro100svitlo** [comment]
any updates???

**Comment by leifcr** [comment]
@pro100svitlo I ended up just writing a sequence number, and adding a check when the app started to see if it should run code that needed to migrate the DB before initializing. A bit hack-ish, but it worked OK for now. I do run the migrations directly on on sqflite before initialzing jaguar-orm.
