### ISSUE TITLE
Unable to use Jaguar orm in a stateful widget in flutter, (it crashes)

### ISSUE THREAD

**Issue by eshiett1995** [jaguar-orm/sqflite#8]
after following your code i was able to add jaguar with sqflite in my project (in my void main() async {} function)
But problem came when i tried to use the code in my stateful widget in flutter. I want to be able to load a list of objects from my database and populate my listview.

I tried the following code 
`[import 'dart:convert';
import 'dart:io';

import 'package:first_app/dao/UserDAO.dart';
import 'package:first_app/models/User.dart';
import 'package:first_app/models/rest-models/response/UserPaginationModel.dart';
import 'package:first_app/network/api/ApiHelper.dart';
import 'package:flutter/material.dart';

import 'package:jaguar_query_sqflite/jaguar_query_sqflite.dart';
import 'package:path/path.dart' as path;
import 'package:sqflite/sqflite.dart';

class Friends extends StatefulWidget {
  @override
  State<StatefulWidget> createState() {
    return new _Friends();
  }
}

class _Friends extends State<Friends> {
  List<User> friendList = [];

  void getFriendsFromDatabase() async {
    SqfliteAdapter _adapter;

    var dbPath = await getDatabasesPath();

    _adapter = SqfliteAdapter(path.join(dbPath, "gambeatDB.db"));

    final userBean = UserBean(_adapter);

    UserDAO userDAO = await userBean.find(1);

    setState(() {
      print(userDAO.id);
    });

  }

  
  @override
  void initState() {
    // TODO: implement initState
    super.initState();

    getFriendsFromDatabase();
  }

  @override
  Widget build(BuildContext context) {
    void friendPanelTapped() {
      showModalBottomSheet(
          context: context,
          builder: (builder) {
            return new Container(
              color: Colors.white,
              child: new Column(
                mainAxisSize: MainAxisSize.min,
                children: <Widget>[
                  SizedBox(
                    height: 20.0,
                  ),
                  Text("SELECT AN OPTION:"),
                  ListTile(
                    leading: Icon(Icons.account_circle),
                    title: Text("Profile"),
                  ),
                  ListTile(
                    leading: Icon(Icons.message),
                    title: Text("Message"),
                  ),
                  ListTile(
                    leading: Icon(Icons.reply),
                    title: Text("Unfollow"),
                  ),
                ],
              ),
            );
          });
    }

    return ListView.builder(
        itemCount: friendList == null ? 0 : friendList.length,
        itemBuilder: (BuildContext context, int index) {
          return GestureDetector(
            onTap: friendPanelTapped,
            child: Card(
              margin: EdgeInsets.symmetric(vertical: 15.0, horizontal: 10.0),
              elevation: 3.0,
              child: Padding(
                  padding: EdgeInsets.all(15.0),
                  child: Row(
                    children: <Widget>[
                      new CircleAvatar(
                        radius: 35.0,
                        backgroundImage: AssetImage('images/chris.jpg'),
                      ),
                      Padding(
                        padding: EdgeInsets.only(right: 10.0),
                      ),
                      Column(
                        crossAxisAlignment: CrossAxisAlignment.start,
                        children: <Widget>[
                          Text(
                            "${friendList[index].firstName} ${friendList[index].lastName}",
                            textAlign: TextAlign.left,
                            style: TextStyle(fontWeight: FontWeight.bold),
                          ),
                          SizedBox(
                            height: 5.0,
                          ),
                          Text(
                            friendList[index].userName,
                            textAlign: TextAlign.left,
                            style: TextStyle(color: Colors.black54),
                          ),
                          SizedBox(
                            height: 5.0,
                          ),
                          Row(
                            mainAxisAlignment: MainAxisAlignment.start,
                            children: <Widget>[
                              Icon(
                                Icons.location_on,
                                color: Colors.blue,
                              ),
                              Text(
                                friendList[index].country,
                                textAlign: TextAlign.left,
                                style: TextStyle(color: Colors.black54),
                              ),
                            ],
                          )
                        ],
                      )
                    ],
                  )),
            ),
          );
        });
  }
}
`](url)

but the code always crashes,  how best can i used jaguar in a stateful widget  ?

**Comment by tejainece** [comment]
Hi,

Did you fix it?
